### ISSUE TITLE
Latest version fails recognize test data 

### ISSUE THREAD

**Issue by tomsains** [zebrain-lab/Toolbox-Romano-et-al#1]
Hello,
I have recently downloaded the latest version of the toolbox.
When trying to use the FindArtifacts or FindROIs functions on the test data (OT_reg_smooth.tif) the following error is returned:

Error using imfinfo (line 112)
Unable to determine file format.

Error in FindROIs (line 52)
tiffInfo = imfinfo(fileName);

This error does not occur with the version of the toolbox which i downloaded a month ago.
Any ideas as to what is causing this error?

I would usually correct the problem myself and submit a pull request but unfortunately i do not use MatLab.

**Comment by sebromano** [comment]
Hello tomsains,
first of all sorry for the delay of my answer. Somehow, I missed the notification of the Issue you point out, and only now I came across your message.
I couldn't reproduce the bug, I had no problem when running the software.
The problem that you are having is most probably due to the fact that you may have tried to clone the whole repository by clicking on the "Clone or download" button in GitHub. Unfortunately, GitHub does not allow downloading files larger than 50MB this way, so when you cloned the complete repository you must have obtained a zip file containing a 134 bytes "dummy" file for the test data. Check the file size of OT_reg_smooth.tif, it should be 394MB. 
In fact, there are 3 large files on the repository: "OT.tif" and "OT_reg_smooth.tif" in the "Test Data" folder, and "OT_reg_smooth_RASTER.mat" in the "Test Data/Processed files" folder. 
To download the correct version of these large files, you should individually click on the corresponding links in the repository (e.g., navigate to "Test Data", click on "OT.tif" and then on "Download").
I am sorry for the inconvenience, but this is how GitHub works. To avoid future issues, I'll put a warning about this in the Readme file.
