### ISSUE TITLE
matlab error during fluorescence processing 

### ISSUE THREAD

**Issue by Callahanra** [zebrain-lab/Toolbox-Romano-et-al#2]
Hi,

I have been testing out your toolbox on zebrafish gcamp6f light sheet data and I'm running into issues at the ROI fluorescence processing steps. This has occurred with different videos and only when I set the sampling frequency to 50 Hz.  It doesn't occur if I leave it set to 4 Hz but then I am assuming I will need to correct the time data later. It appears to be failing at step 25. 

I've copied the MATLAB Error info below. 
I appreciate any help you can give.

Thanks,
Rebecca

>> ProcessFluorescenceTraces
Step 1: Sanity test for ROIs and calculation relative fluorescence variation.
1.1 Calculating fluorescence baseline of ROIs...
Index exceeds matrix dimensions.

Error in SanityTest (line 55)
        smoothBaseline(:,j)=[temp(1)*ones(wdw,1) ; temp; temp(end)*ones(wdw,1)];

Error in ProcessFluorescenceTraces (line 70)
[fluoTraces,F0,smoothBaseline,deletedCells]=SanityTest(filenameALL_CELLS,params);

**Comment by sebromano** [comment]
Hello Rebecca,

the program seems to be failing when trying to calculate the slow variations in fluorescence baseline. This is usually done to be able to work with long imaging videos where the baseline may change with time. However, checking the code it seems that the program may run into a bug if the imaging data shorter than 15 seconds. Is this your case? You are able to "workaround" this issue by setting a sampling frequency at the default of 4 Hz because then the program will handle the imaging data as if it was longer in duration, but this is artificial and not advised. 
Anyway, I'll correct the code asap so that it can handle these situations (probably on monday, I am not at the lab right now). I'll let you know.

Finally, regarding the difficulty of working on the toolbox example files (as you mentioned in your mail): you are probably working with corrupted versions of the tif example files. Some people have commented on this issue when downloading the toolbox by clicking on the "Clone or Download" button in github. Please see the updated Readme in github where I explain: 

"Unfortunately, GitHub does not allow downloading files larger than 50MB this way, you will obtain a compressed zip file where files >50MB will be replaced by 134-bytes "dummy" files. The test data has 3 files larger than 50MB: "OT.tif" and "OT_reg_smooth.tif" in the "Test Data" folder, and "OT_reg_smooth_RASTER.mat" in the "Test Data/Processed files" folder. To download the correct version of these large files, you should individually click on the corresponding links in the repository (e.g., navigate to "Test Data", click on "OT.tif" and then on "Download"), and replace the "dummy" 134-bytes files on your computer."

Let me know if that works for you.
Best,
Sebastian.

**Comment by Callahanra** [comment]
Hi Sebastian,

That absolutely is the case, I cut down my videos to 10 s so I could swiftly run through and test out the toolbox, though I do occasionally have videos that are not much longer than 15 s. 

I did download the individual file as described in the Readme and the previous Issue, but they are the same 134 byte dummy files. This is also the case if I wget the files (though smaller files appear to download just fine this way).  

Thanks a lot for your help!
-Rebecca

**Comment by sebromano** [comment]
Hi Rebecca,

I think I fixed the issue. Please replace the old SanityTest.m from the "Toolbox Software" folder with the new version of SanityTest.m. Let me know if that works for you.

Lastly, I can confirm the problem that you describe with the test data files. It's an issue with storage of large files in the github, as expected. I'll solve this soon, probably giving some instructions on how to download the toolbox repository through the [Git Large File Storage](https://git-lfs.github.com/), but this has to be done manually through the command line. Alternatively, I'll store these large files in another site. I'll let you know.

Best,
Sebastian.

**Comment by sebromano** [comment]
Hi Rebecca,

regarding the test data files, please see the updated Installation instructions in the README file for a link to download the test dataset. Basically, you can download it from: http://www.zebrain.biologie.ens.fr/codes/ToolboxRomanoetal_TestData.zip

Best,
Sebastian.

**Comment by Callahanra** [comment]
Thanks Sebastian!
