### ISSUE TITLE
 RunResponseMapping

### ISSUE THREAD

**Issue by mc3515** [zebrain-lab/Toolbox-Romano-et-al#4]
Whenever I run RunResponseMapping.m I get back the error:

Error using patch
Color value contains NaN, or element out of range 0.0 <=
value <= 1.0

Error in plotResponses (line 29)
        
Error in remapResponseColors (line 107)

Error in MapResponses (line 177)

Error in RunResponseMapping (line 3)

**Comment by bhopp002** [comment]
Hi, I'm having the exact same problem with RunResponseMapping.m. Did you ever figure out how to solve this?

**Comment by sebromano** [comment]
Hi,

it's hard to diagnose the error without further information. There are multiple possibilities for obtaining that kind of error. What's happening is that for some reason, for at least one of the responses, it's obtaining a NaN and/or a value ouf of range.
First thing that we should check is:
1) Are there any NaNs in your raster?
2)  Could you paste here the values of the variable roiHSV?
to have access to this variable, you should run MapResponses as a script, not a function: open MapResponses in the editor window, select with your mouse all code lines between line 2 and line 166, right click on this selection and click on "Evaluate selection", and then call roiHSV in the command window to obtain its values.

**Comment by slceto** [comment]
I'm not sure what the actual problem is, but I've had this too and found that increasing the 'Duration of time window after event for ROI response calculation (s)' can get around this.  I had lowered it to 1 second and got your error, but going back to the default of 3 seconds made it work again.

**Edit**:  So I've been working on a modified version of this script to plot the max response amplitude rather than the average dff, and I kept getting this error.  I finally figured out that in line 82 of remapResponseColors, all of my indsCutUp were being reassigned to a value of "1" because all of my max dffs were over 1.  This then screwed up the rest of the function for me because every value was converted to '1' a couple lines later, after which the minimum value of the column ('1') was subtracted from the column, thus making every value '0'.  When line 87 then divided by the max, which was now '0', I finally generated the NaN values in roiHSVRescaled that create the error message.

TO FIX THIS:  I increased the value of cutUp on line 171 of mapResponses from '1' to '5'.  The default value of '1' is kind of arbitrary, and should be adjusted to fit your data.  Unfortunately, in this case it breaks the script if it doesn't fit.
