### ISSUE TITLE
ROI deltaF/F0 plot not showing up

### ISSUE THREAD

**Issue by maggiecdagger** [zebrain-lab/Toolbox-Romano-et-al#6]
Hi,
what are some of the potential causes for deltaF/F0 plots to not show up? Also I went back to the paper that you referred to in the tutorial paper for the GCaMP3 tau - I am using GCaMP6 (fast), wondering what would be the tau for it.

Thank you!
Maggie

**Comment by slceto** [comment]
One problem I've run into is if you ask it to plot more example traces than ROIs you actually have.  Since the default is 20, if you don't have at least 20 good (yellow outline in image that pops up) ROIs, it will give an error and not plot anything if you don't change the number of traces to plot when asked.

I'm also using GCaMP6f and found a tau of 0.142 in the Supplementary Table 3 of the original Chen et al 2013 GCaMP6 paper.  This is for in vivo imaging in mouse V1.

Edit:  After going back over the tutorial, I realized the tau value doesn't say half-decay, but just decay.  I guess this should be doubled to 0.284.  The default value is 0.38, which it says comes from the value reported in one of the references for GCaMP3.  I checked that out and it gives a T(1/2) of 0.16 for Purkinje cells and 0.22 for layer 2/3 cortical neurons.  If you double these and average them you get 0.38.
